import type { Metadata } from "next";

import {
  Fraunces,
  Geist,
  Geist_Mono,
  Labrada,
  Griffy,
} from "next/font/google";

import Header from "./components/Header";
import "./globals.css";

const griffy = Griffy({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-griffy",
});

const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
  weight: ["400", "600"],
});

const labrada = Labrada({
  variable: "--font-labrada",
  subsets: ["latin"],
  weight: ["400", "600"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`
        ${geistSans.variable}
        ${geistMono.variable}
        ${fraunces.variable}
        ${labrada.variable}
        ${griffy.variable}
        h-full
        antialiased
      `}
    >
      <body className="min-h-full flex flex-col">
        <Header />

        {children}
      </body>
    </html>
  );
}
